name: Hazelcast
description: |
  Hazelcast is an open source in-memory data grid based on Java.
version: 3.12
category: Data Grid
maintainer: hbaos
license: # The license
projectURL: # A URL related to the catalog entry